const nameGirl = 'To : Duyen';
const giftUrl = 'https://www.facebook.com/groups/165460116804572';
const eventName = 'Happy 8/3 !!!';
const titleCard = 'For Vit girls';
const contentCard = '</br>Cảm ơn cậu đã đến bên chúng tớ ! </br> Mọi cảm giác và mọi khoảnh khắc hạnh phúc sẽ không được thực sự trọn vẹn nếu như thiếu cậu trong đó! Chúc cậu có ngày 8/3 và 364 ngày còn lại trong năm hạnh phúc. </br></br>         From VIT Boy with luv !';
const giftImage = 'dha.png';
const giftBg = 'valentines.jpg'
const base64 = '';
const giftImageBase64 = "data:image/png;base64, " + base64;